# Generated by Django 5.1.8 on 2025-04-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('majors', models.CharField(help_text='Comma-separated if multiple', max_length=200)),
                ('academic_interests', models.TextField(help_text='Comma-separated list')),
                ('non_academic_interests', models.TextField(help_text='Comma-separated list')),
                ('current_classes', models.TextField(help_text='Comma-separated list')),
            ],
        ),
    ]
